composer.json

| Branch?       | 6.2.x
| BC breaks?    | no 
| Fixed issues  | 
Remove the ESONO packagist entry (isn't interesting for everyone else).

Remove ESONO packagist

---

src/AppBundle/Bridge/Chameleon/Migration/Script/update-1535695117.inc.php

| Fixed issues  | chameleon-system/chameleon-system#50
Show manufacturer name in article table (in Demo shop).

ref #50: Add manufacturer name to table display

---

app/config/config.yml

ref #63: Disable WYSIWYG script tags

---

app/config/routing_dev.yml

ref #210: Adjust web debug toolbar routing

---

README.md

Extend information in README

---

app/AppKernel.php
app/config/config.yml
app/config/config_dev.yml

ref #261: Configure DoctrineBundle

---

app/config/config.yml
app/config/config_dev.yml
app/config/config_prod.yml
app/config/config_test.yml

92 use monolog logging

---

app/AppKernel.php
src/extensions/objectviews/TCMSFields/TCMSFieldMediaWithImageCrop
src/extensions/snippets-cms/imageCrop

ref #292: Add ImageCropBundle

---

app/config/config.yml
app/config/config_dev.yml
app/config/config_prod.yml
app/config/config_test.yml

ref #92: Add default logging config

---

app/AppKernel.php

Add DoctrineCacheBundle

---

app/config/config.yml

ref #65: Remove config as it is now the default value

---

src/AppBundle/Bridge/Chameleon/Migration/Script/update-1554708763.inc.php

ref #323: Remove outdated module_cms_search table

---

app/config/config.inc.php

| BC breaks?    | yes - unlikely; if you use .intra in your domain name only
| Fixed issues  | #416

ref #416: Use APP_ENV or SYMFONY_ENV for determining the dev environment

---

app/config/config.inc.php

ref #416: Keep dev mode false if nothing is configured

---

src/AppBundle/Bridge/Chameleon/Migration/Script/update-1570449006.inc.php

| Branch        | features / 6.3.x for bug fixes 
| New feature?  | no 
| BC breaks?    | no     
| Deprecations? | no 
| Fixed issues  | #33265
Basket: Telephone-Order had an unknown telephone-no. Changed to Esono Phone-No.

ref #33265: telephone-order: change of telephone-no

---

app/config/config.inc.php

| Branch        | 6.3.x
| Fixed issues  | #575

ref #575: Make demo shop login case-insensitive

---

.gitignore
app/AppKernel.php
composer.json
composer.lock
web/favicon.ico

| Branch        | master 
| New feature?  | no 
| BC breaks?    | no  
This will make the demo shop work with the latest chameleon upgrade to symfony 4.4

Symfony44 upgrade

---

app/config/parameters.yml.dist

ref #521: Allow parameter processing during composer run

---

composer.json

Upgrade composer.json to use console directly

change scripts section to use console directly

---

app/config/config_prod.yml

| Branch        | 6.3.x
| Fixed issues  | #608

608 proper default logging

---

src/extensions/snippets-cms/imageCrop
src/extensions/snippets-cms/mediaManager

| Branch        | 7.0.x
| BC breaks?    | no - only if these symlinks are used for something else than rendering views...
| Fixed issues  | #648

ref #648: Support bundle resources as "module type" for view search

---

.github/ISSUE_TEMPLATE/bc_break_report.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Adapt bug/issue templates
